export const GET_MOVIES_REQUESTED = "GET_MOVIES_REQUESTED";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAILED = "GET_MOVIES_FAILED";

export const GET_MOVIEDETAILS_REQUESTED = "GET_MOVIEDETAILS_REQUESTED";
export const GET_MOVIEDETAILS_SUCCESS = "GET_MOVIEDETAILS_SUCCESS";
export const GET_MOVIEDETAILS_FAILED = "GET_MOVIEDETAILS_FAILED";

export const GET_LATEST_MOVIES_REQUESTED = "GET_LATEST_MOVIES_REQUESTED";
export const GET_LATEST_MOVIES_SUCCESS = "GET_LATEST_MOVIES_SUCCESS";
export const GET_LATEST_MOVIES_FAILED = "GET_LATEST_MOVIES_FAILED";

export const GET_LATEST_MOVIEDETAILS_REQUESTED =
  "GET_LATEST_MOVIEDETAILS_REQUESTED";
export const GET_LATEST_MOVIEDETAILS_SUCCESS =
  "GET_LATEST_MOVIEDETAILS_SUCCESS";
export const GET_LATEST_MOVIEDETAILS_FAILED = "GET_LATEST_MOVIEDETAILS_FAILED";

export const GET_UPCOMING_MOVIES_REQUESTED = "GET_UPCOMING_MOVIES_REQUESTED";
export const GET_UPCOMING_MOVIES_SUCCESS = "GET_UPCOMING_MOVIES_SUCCESS";
export const GET_UPCOMING_MOVIES_FAILED = "GET_UPCOMING_MOVIES_FAILED";

export const GET_UPCOMING_MOVIEDETAILS_REQUESTED =
  "GET_UPCOMING_MOVIEDETAILS_REQUESTED";
export const GET_UPCOMING_MOVIEDETAILS_SUCCESS =
  "GET_UPCOMING_MOVIEDETAILS_SUCCESS";
export const GET_UPCOMING_MOVIEDETAILS_FAILED =
  "GET_UPCOMING_MOVIEDETAILS_FAILED";

export const GET_EVENTS_REQUESTED = "GET_EVENTS_REQUESTED";
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const GET_EVENTS_FAILED = "GET_EVENTS_FAILED";
