export const GET_MOVIES_REQUESTED = "GET_MOVIES_REQUESTED";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAILED = "GET_MOVIES_FAILED";

export const GET_MOVIEDETAILS_REQUESTED = "GET_MOVIEDETAILS_REQUESTED";
export const GET_MOVIEDETAILS_SUCCESS = "GET_MOVIEDETAILS_SUCCESS";
export const GET_MOVIEDETAILS_FAILED = "GET_MOVIEDETAILS_FAILED";
